[package]
name = "bevy_pixelmap"
version = "0.1.0"
resolver = "2"
edition = "2021"

[dependencies]
bevy = "^0.14"
bevy-inspector-egui = "^0.26"
bytemuck = "1.18.0"
lazy_static = "1.5.0"
line_drawing = "1.0.0"
rand = "0.8.5"
wgpu = "0.20.1"
