[package]
name = "simple_example"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.2"
bevy-inspector-egui = "0.26.0"
bevy_pixelmap = { path = "../../" }
line_drawing = "1.0.0"
rand = "0.8.5"
